name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          default-branch: main
          release-type: node
  npm:
    needs: release
    if: contains(fromJson(needs.release.outputs.paths_released), 'packages/core')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm publish --access=public --workspace=packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
