name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_cli:
        type: boolean
        description: release packages/cli even if it normally wouldn't (e.g. due to release-please checks)
        default: false
      release_core:
        type: boolean
        description: release packages/core even if it normally wouldn't (e.g. due to release-please checks)
        default: false

jobs:
  env-setup:
    runs-on: ubuntu-latest
    outputs:
      release_cli: ${{ steps.set-output-defaults.outputs.release_cli }}
      release_core: ${{ steps.set-output-defaults.outputs.release_core }}
    steps:
      - name: set release_cli with default value
        id: set-release_cli-defaults
        run: |    
          # If workflow_dispatch, use inputs (left), if other trigger, use default env (right)
          echo "::set-output name=release_cli::${{ github.event.inputs.release_cli || contains(fromJson(needs.release.outputs.paths_released), 'packages/cli') }}"
      - name: set release_core with default value
        id: set-release_core-defaults
        run: |    
          # If workflow_dispatch, use inputs (left), if other trigger, use default env (right)
          echo "::set-output name=release_core::${{ github.event.inputs.release_core || contains(fromJson(needs.release.outputs.paths_released), 'packages/core') }}"
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          default-branch: main
          release-type: node
  npm-core:
    name: npm publish @web3-storage/content-claims
    needs: release
    if: release_core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=packages/core
      - run: npm publish --access=public --workspace=packages/core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  npm-cli:
    name: npm publish @web3-storage/content-claims-cli
    needs: release
    if: release_cli
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --workspace=packages/cli
      - run: npm publish --access=public --workspace=packages/cli --provenance
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
